FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    wget \
    vim \
    sudo \
    python3 \
    netcat-openbsd \
    net-tools \
    cmake \
    build-essential \
    grep \
    && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash -G sudo user

USER user
WORKDIR /home/user

#exposing port for file transfer
EXPOSE 44444
