FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    wget \
    vim \
    sudo \
    python \
    netcat-openbsd \
    net-tools \
    git \
    cmake \
    build-essential \
    python3 \
    python3-pip \
    ipython \
    ipython-notebook \
    grep \
    && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash -G sudo user

#making sudo passwordless
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user
WORKDIR /home/user

#exposing port for file transfer
EXPOSE 44444
